### ISSUE TITLE
Add Site - encryption key javascript error

### ISSUE THREAD

**Issue by budda** [jkswoods/samurai#102]
When attepting to add a new site and giving an encryption key of "passwordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpasswordpassword"

Nothing happens on screen but I can see in the dev console:

```Uncaught SyntaxError: Unexpected token ILLEGAL```

The error point to line 114 which contains

```
 <script type='text/javascript'>Materialize.toast("Unable to connect to the site, check the encryption key is correct and
        Samurai is configured properly to access the site", 5000);</script>
```

I am unable to proceed with adding a site.

**Comment by budda** [comment]
This was using master branch.

**Comment by jkswoods** [comment]
Fixed
