### ISSUE TITLE
Installation of release/0.3 fails with an ajax 500 error during setup wizard

### ISSUE THREAD

**Issue by budda** [jkswoods/samurai#103]
Whilst going through the drupal install wizard i hit an ajax dialog error which appears to be due to a HTTP 500 response.

![screen shot 2016-04-19 at 16 22 28](https://cloud.githubusercontent.com/assets/104929/14644772/28b71b8a-064b-11e6-97ad-6a18817ae22b.png)

**Comment by budda** [comment]
This process worked fine with the master branch / 0.2 version

**Comment by jkswoods** [comment]
The composer_manager module was not added to the profile dependencies list, causing errors when it tried to load a third party library managed by composer.

**Comment by budda** [comment]
What do I need to do to fix this if i've got a partially working setup?

**Comment by jkswoods** [comment]
The fix has been added to the install profile steps so it will require a database drop and removal of the configuration stored inside settings.php for it to be run.

- The drush composer extension will need to be downloaded as of this update: `cd /etc/drush && drush dl composer-8` ensure it is the 8.x-* branch. 
- Run the make to download the new projects `drush make profiles/samurai/drupal-org.make --no-core -y`

**Comment by budda** [comment]
Project composer (8.x-1.4) downloaded to /home/vagrant/.drush/composer.                [success]

Git pulled latest bits n bobs.

```
 .gitignore                                         |   2 +
 README.md                                          |  23 +--
 build.sh                                           |   4 -
 composer.json                                      |  10 +
 .../features/composer_assets/composer_assets.info  |   1 +
 .../composer_assets/composer_assets.strongarm.inc  |   9 +-
 .../security_samurai_codeception.module            |  11 +-
 .../docker/images/default/Dockerfile               |  78 --------
 .../docker/images/default/example.txt              |   9 -
 .../includes/SamuraiDocker.php                     |  10 +-
 .../security_samurai_docker.module                 | 219 +++++++++++++--------
 .../security_samurai_docker.profile.inc            |   8 +-
 .../security_samurai_gitapi.profile.inc            |  16 +-
 samurai.info                                       |   2 +
 samurai.profile                                    |  19 +-
 .../metallurgy_samurai/stylesheets/css/build.css   |  92 +++++----
 .../stylesheets/scss/_layout.scss                  |   7 +-
 .../stylesheets/scss/_style.scss                   |  80 ++++----
 .../stylesheets/scss/_variables.scss               |   2 +-
 .../templates/entity/entity--client-site.tpl.php   |  12 +-
 .../page/page--client-site--config--add.tpl.php    |   8 +-
 .../page--client-site--config--manage--%.tpl.php   |   8 +-
 .../page--jobs--environments--config--add.tpl.php  |   8 +-
 .../page/page--jobs--images--config--add.tpl.php   |   8 +-
 .../templates/page/page--user--%.tpl.php           |   8 +-
 .../metallurgy_samurai/templates/page/page.tpl.php |   8 +-
 vendor/README.txt                                  |   1 +
 27 files changed, 321 insertions(+), 342 deletions(-)
```

Emptied DB.
Re-ran make.
Installed Samurai.

It got a bit longer in to the "Create Default Image" step this time, but ended with the same HTTP 500 Ajax dialog pop up.

**Comment by budda** [comment]
After the change of www-data and drush composer on the Vagrant side it now appears to go through the wizard in full without error.

**Comment by jkswoods** [comment]
Great, I'll add that step to the docs.
