### ISSUE TITLE
Issue with scanning a new site for projects.

### ISSUE THREAD

**Issue by jkswoods** [jkswoods/samurai#8]
Warning: Invalid argument supplied for foreach() in samurai_get_project_latest_version() (line 606 of /webroot/samurai.drupal.dev/sites/samurai/modules/security_samurai_controller/security_samurai_controller.fetch.inc).

Warning: Invalid argument supplied for foreach() in samurai_get_project_latest_secure_version() (line 646 of /webroot/samurai.drupal.dev/sites/samurai/modules/security_samurai_controller/security_samurai_controller.fetch.inc).

**Comment by ixisbigman** [comment]
I think I may have solved this, I shall pick it up next week

**Comment by jkswoods** [comment]
Fixed in https://github.com/jkswoods/samurai/pull/11
Closing
